import { floorplanRoom } from "./assets/types"

export const floorplanRooms: floorplanRoom[] = [
    /* --- Ground floor --- */
    {
        id: 1,
        floor: 0,
        desc: "S.30",
        short: "rs30",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -15,
            columnStart: -7,
            rowEnd: -8,
            columnEnd: -1
        },
    },
    {
        id: 2,
        floor: 0,
        desc: "S.31",
        short: "rs31",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -8,
            columnStart: -7,
            rowEnd: -1,
            columnEnd: -1,
        },
    },
    {
        id: null,
        floor: 0,
        desc: "WC and stairs",
        short: "wcs1",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: -7,
            columnStart: -11,
            rowEnd: -1,
            columnEnd: -7,
        },
    },
    {
        id: null,
        floor: 0,
        desc: "WC and stairs",
        short: "wcs2",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: -7,
            columnStart: 6,
            rowEnd: -1,
            columnEnd: 9,
        },
    },
    {
        id: null,
        floor: 0,
        desc: "WC and stairs",
        short: "wcs4",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 1,
            columnStart: -11,
            rowEnd: 7,
            columnEnd: -7,
        },
    },
    {
        id: null,
        floor: 0,
        desc: "Printer",
        short: "printerS",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 5,
            columnStart: -13,
            rowEnd: 7,
            columnEnd: -11,
        },
    },
    {
        id: null,
        floor: 0,
        desc: "",
        short: "administration-area-1",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 1,
            columnStart: -7,
            rowEnd: 15,
            columnEnd: -1,
        },
    },
    {
        id: null,
        floor: 0,
        desc: "",
        short: "administration-area-2",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: -9,
            columnStart: 1,
            rowEnd: -1,
            columnEnd: 6,
        },
    },
    {
        id: null,
        floor: 0,
        desc: "",
        short: "administration-area-3",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 11,
            columnStart: 1,
            rowEnd: -9,
            columnEnd: 9,
        },
    },
    {
        id: null,
        floor: 0,
        desc: "",
        short: "administration-area-4",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 7,
            columnStart: 1,
            rowEnd: 11,
            columnEnd: 11,
        },
    },
    {
        id: null,
        floor: 0,
        desc: "",
        short: "administration-area-5",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 1,
            columnStart: 1,
            rowEnd: 7,
            columnEnd: -11,
        },
    },
    {
        id: null,
        floor: 0,
        desc: "",
        short: "holeS",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 11,
            columnStart: 9,
            rowEnd: -9,
            columnEnd: -11,
        },
    },/* --- 1. floor --- */
    {
        id: 3,
        floor: 1,
        desc: "1.01",
        short: "r101",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -8,
            columnStart: -7,
            rowEnd: -1,
            columnEnd: -1,
        },
    },
    {
        id: null,
        floor: 1,
        desc: "1.08 photo studio",
        short: "r108",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: -5,
            columnStart: 15,
            rowEnd: -1,
            columnEnd: 19,
        },
    },
    {
        id: null,
        floor: 1,
        desc: "WC and stairs",
        short: "wc11",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: -7,
            columnStart: -11,
            rowEnd: -1,
            columnEnd: -7,
        },
    },
    {
        id: 4,
        floor: 1,
        desc: "1.12",
        short: "r112",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -7,
            columnStart: 9,
            rowEnd: -1,
            columnEnd: 15,
        },
    },
    {
        id: null,
        floor: 1,
        desc: "WC and elevator",
        short: "wc12",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: -7,
            columnStart: 6,
            rowEnd: -1,
            columnEnd: 9,
        },
    },
    {
        id: 5,
        floor: 1,
        desc: "1.16",
        short: "r116",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -9,
            columnStart: 1,
            rowEnd: -1,
            columnEnd: 6,
        },
    },
    {
        id: 6,
        floor: 1,
        desc: "1.17",
        short: "r117",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -11,
            columnStart: 5,
            rowEnd: -9,
            columnEnd: 7,
        },
    },
    {
        id: 7,
        floor: 1,
        desc: "1.18",
        short: "r118",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -11,
            columnStart: 3,
            rowEnd: -9,
            columnEnd: 5,
        },
    },
    {
        id: 8,
        floor: 1,
        desc: "1.19",
        short: "r119",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -11,
            columnStart: 1,
            rowEnd: -9,
            columnEnd: 3,
        },
    },
    {
        id: 9,
        floor: 1,
        desc: "1.24",
        short: "r124",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 1,
            columnStart: 1,
            rowEnd: 9,
            columnEnd: 6,
        },
    },
    {
        id: null,
        floor: 1,
        desc: "WC and stairs",
        short: "wc13",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 1,
            columnStart: 6,
            rowEnd: 7,
            columnEnd: 9,
        },
    },
    {
        id: 10,
        floor: 1,
        desc: "1.27",
        short: "r127",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 1,
            columnStart: 9,
            rowEnd: 7,
            columnEnd: 15,
        },
    },
    {
        id: null,
        floor: 1,
        desc: "Printer",
        short: "printer1",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 1,
            columnStart: 15,
            rowEnd: 4,
            columnEnd: 17,
        },
    },
    {
        id: 11,
        floor: 1,
        desc: "1.28",
        short: "r128",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 9,
            columnStart: 12,
            rowEnd: 11,
            columnEnd: 14,
        },
    },
    {
        id: 12,
        floor: 1,
        desc: "1.32",
        short: "r132",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 1,
            columnStart: -13,
            rowEnd: 4,
            columnEnd: -11,
        },
    },
    {
        id: null,
        floor: 1,
        desc: "WC and stairs",
        short: "wc14",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 1,
            columnStart: -11,
            rowEnd: 7,
            columnEnd: -7,
        },
    },
    {
        id: 13,
        floor: 1,
        desc: "1.38",
        short: "r138",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 1,
            columnStart: -7,
            rowEnd: 8,
            columnEnd: -1,
        },
    },
    {
        id: 14,
        floor: 1,
        desc: "1.39",
        short: "r139",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 8,
            columnStart: -7,
            rowEnd: 15,
            columnEnd: -1,
        },
    },
    {
        id: 15,
        floor: 1,
        desc: "1.40",
        short: "r140",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 12,
            columnStart: -11,
            rowEnd: 14,
            columnEnd: -9,
        },
    },
    {
        id: 16,
        floor: 1,
        desc: "1.42",
        short: "r142",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -15,
            columnStart: -7,
            rowEnd: -8,
            columnEnd: -1,
        },
    },
    {
        id: 17,
        floor: 1,
        desc: "1.43",
        short: "r143",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 9,
            columnStart: 5,
            rowEnd: 11,
            columnEnd: 7,
        },
    },
    {
        id: 18,
        floor: 1,
        desc: "1.44",
        short: "r144",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 9,
            columnStart: 3,
            rowEnd: 11,
            columnEnd: 5,
        },
    },
    {
        id: null,
        floor: 1,
        desc: "",
        short: "hole1",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 9,
            columnStart: 11,
            rowEnd: -11,
            columnEnd: -9,
        },
    }, /* --- 2. floor --- */
    {
        id: 19,
        floor: 2,
        desc: "2.01",
        short: "r201",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -8,
            columnStart: -7,
            rowEnd: -1,
            columnEnd: -1,
        },
    },
    {
        id: null,
        floor: 2,
        desc: "WC and stairs",
        short: "wc21",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: -7,
            columnStart: -11,
            rowEnd: -1,
            columnEnd: -7,
        },
    },
    {
        id: 20,
        floor: 2,
        desc: "2.07",
        short: "r207",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -11,
            columnStart: -14,
            rowEnd: -9,
            columnEnd: -12,
        },
    },
    {
        id: 21,
        floor: 2,
        desc: "2.09",
        short: "r209",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -4,
            columnStart: -13,
            rowEnd: -1,
            columnEnd: -11,
        },
    },
    {
        id: null,
        floor: 2,
        desc: "Sevice Desk",
        short: "service-desk",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: -4,
            columnStart: -15,
            rowEnd: -1,
            columnEnd: -13,
        },
    },
    {
        id: 22,
        floor: 2,
        desc: "2.11",
        short: "r211",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -7,
            columnStart: 9,
            rowEnd: -1,
            columnEnd: 15,
        },
    },
    {
        id: null,
        floor: 2,
        desc: "WC and elevator",
        short: "wc22",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: -7,
            columnStart: 6,
            rowEnd: -1,
            columnEnd: 9,
        },
    },
    {
        id: 23,
        floor: 2,
        desc: "2.16",
        short: "r216",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -9,
            columnStart: 1,
            rowEnd: -1,
            columnEnd: 6,
        },
    },
    {
        id: 24,
        floor: 2,
        desc: "2.17",
        short: "r217",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -11,
            columnStart: 1,
            rowEnd: -9,
            columnEnd: 4,
        },
    },
    {
        id: 25,
        floor: 2,
        desc: "2.18",
        short: "r218",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -14,
            columnStart: 9,
            rowEnd: -12,
            columnEnd: 11,
        },
    },
    {
        id: 26,
        floor: 2,
        desc: "2.20",
        short: "r220",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -15,
            columnStart: 1,
            rowEnd: -11,
            columnEnd: 7,
        },
    },
    {
        id: 27,
        floor: 2,
        desc: "2.21",
        short: "r221",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 9,
            columnStart: 1,
            rowEnd: 15,
            columnEnd: 7,
        },
    },
    {
        id: 28,
        floor: 2,
        desc: "2.22",
        short: "r222",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 1,
            columnStart: 1,
            rowEnd: 9,
            columnEnd: 6,
        },
    },
    {
        id: null,
        floor: 2,
        desc: "WC and stairs",
        short: "wc23",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 1,
            columnStart: 6,
            rowEnd: 7,
            columnEnd: 9,
        },
    },
    {
        id: 29,
        floor: 2,
        desc: "2.25",
        short: "r225",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 5,
            columnStart: 9,
            rowEnd: 7,
            columnEnd: 11,
        },
    },
    {
        id: 30,
        floor: 2,
        desc: "2.26",
        short: "r226",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 3,
            columnStart: 9,
            rowEnd: 5,
            columnEnd: 11,
        },
    },
    {
        id: 31,
        floor: 2,
        desc: "2.31",
        short: "r231",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 3,
            columnStart: -13,
            rowEnd: 5,
            columnEnd: -11,
        },
    },
    {
        id: null,
        floor: 2,
        desc: "WC and stairs",
        short: "wc24",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 1,
            columnStart: -11,
            rowEnd: 7,
            columnEnd: -7,
        },
    },
    {
        id: 32,
        floor: 2,
        desc: "2.37",
        short: "r237",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 1,
            columnStart: -7,
            rowEnd: 8,
            columnEnd: -1,
        },
    },
    {
        id: 33,
        floor: 2,
        desc: "2.38",
        short: "r238",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: 8,
            columnStart: -7,
            rowEnd: 15,
            columnEnd: -1,
        },
    },
    {
        id: 34,
        floor: 2,
        desc: "2.41",
        short: "r241",
        bookable: true,
        availability: "available",
        gridCord: {
            rowStart: -15,
            columnStart: -7,
            rowEnd: -8,
            columnEnd: -1,
        },
    },
    {
        id: null,
        floor: 2,
        desc: "",
        short: "hole2",
        bookable: false,
        availability: "unavailable",
        gridCord: {
            rowStart: 11,
            columnStart: 9,
            rowEnd: -9,
            columnEnd: -11,
        },
    },
]